# Generated by Django 5.1 on 2024-09-15 22:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('type_acheteur', models.CharField(max_length=200)),
                ('numero_cni', models.CharField(max_length=200)),
                ('numero_oncc', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('filiale', models.CharField(max_length=200)),
                ('coordonnees_geographiques', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'acheteur',
                'verbose_name_plural': 'acheteurs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('type_cooperative', models.CharField(max_length=200)),
                ('siege_social', models.CharField(max_length=200)),
                ('nom_responssable', models.CharField(max_length=200)),
                ('contact_responssable', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('coordonnees_gps', models.CharField(max_length=200)),
                ('identifiant_unique', models.CharField(max_length=500)),
                ('mot_pass', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(max_length=500)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('numero_cni', models.CharField(max_length=200)),
                ('identifiant_fodecc_cicc', models.CharField(max_length=200)),
                ('numero_telephone', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('adminCoop', 'aAdminCoop'), ('acteur', 'Acteur')], default='acteur', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre_foncier', models.CharField(max_length=200)),
                ('statut', models.CharField(max_length=200)),
                ('coordonnees_polygonales', models.CharField(max_length=200)),
                ('superficie', models.FloatField()),
                ('nombre_arbres', models.IntegerField()),
                ('age_moyen_arbres', models.FloatField()),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteur', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
        migrations.CreateModel(
            name='CooperativeProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arriver_producteur', models.DateField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperativeProd', to='cocoaApp.cooperative')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurCoop', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'CooperativeProducteur',
                'verbose_name_plural': 'CooperativeProducteurs',
            },
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.CharField(max_length=200)),
                ('quantite', models.FloatField(null=True)),
                ('date_creation', models.DateField()),
                ('date_modification', models.DateField()),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteur', to='cocoaApp.acheteur')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=200)),
                ('quantite', models.FloatField()),
                ('type_commercial', models.CharField(max_length=200)),
                ('taux_humidite', models.FloatField()),
                ('date_recolt', models.DateField()),
                ('date_livraison', models.DateField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotCooperative', to='cocoaApp.cooperative')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotParcelle', to='cocoaApp.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotProducteur', to='cocoaApp.producteur')),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotSac', to='cocoaApp.sac')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
            },
        ),
    ]
