# Generated by Django 5.1.1 on 2024-09-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('type_acheteur', models.CharField(max_length=200)),
                ('numero_cni', models.CharField(max_length=200)),
                ('numero_oncc', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('filiale', models.CharField(max_length=200)),
                ('coordonnees_geographiques', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'acheteur',
                'verbose_name_plural': 'acheteurs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('type_cooperative', models.CharField(max_length=200)),
                ('siege_social', models.CharField(max_length=200)),
                ('nom_responssable', models.CharField(max_length=200)),
                ('contact_responssable', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('coordonnees_gps', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(max_length=500)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('numero_cni', models.CharField(max_length=200)),
                ('identifiant_fodecc_cicc', models.CharField(max_length=200)),
                ('numero_telephone', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('arrondissement', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre_foncier', models.CharField(max_length=200)),
                ('statut', models.CharField(max_length=200)),
                ('coordonnees_polygonales', models.CharField(max_length=200)),
                ('superficie', models.FloatField()),
                ('nombre_arbres', models.IntegerField()),
                ('age_moyen_arbres', models.FloatField()),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteur', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
        migrations.CreateModel(
            name='CooperativeProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arriver_producteur', models.DateField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperativeProd', to='cocoaApp.cooperative')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurCoop', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'CooperativeProducteur',
                'verbose_name_plural': 'CooperativeProducteurs',
            },
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.CharField(max_length=200)),
                ('quantite', models.FloatField(null=True)),
                ('date_creation', models.DateField()),
                ('date_modification', models.DateField()),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteur', to='cocoaApp.acheteur')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
            },
        ),
        migrations.CreateModel(
            name='lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=200)),
                ('quantite', models.FloatField()),
                ('type_commercial', models.CharField(max_length=200)),
                ('taux_humidite', models.FloatField()),
                ('date_recolt', models.DateField()),
                ('date_livraison', models.DateField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotCooperative', to='cocoaApp.cooperative')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotParcelle', to='cocoaApp.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotProducteur', to='cocoaApp.producteur')),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotSac', to='cocoaApp.sac')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
            },
        ),
    ]
