# Generated by Django 5.1 on 2024-09-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='identifiant_unique',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='mot_pass',
        ),
    ]
