# Generated by Django 5.1.1 on 2024-09-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.IntegerField()),
                ('mot_de_pass', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('etat_compte', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categorie_article',
                'verbose_name_plural': 'Categorie_articles',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.IntegerField()),
                ('mot_de_pass', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Couturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.IntegerField()),
                ('mot_de_pass', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('specialite', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Couturier',
                'verbose_name_plural': 'Couturiers',
            },
        ),
        migrations.CreateModel(
            name='Mode_Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Mode_Paiement',
                'verbose_name_plural': 'Mode_Paiements',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_tel', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_admin', to='cocoaApp.administrateur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_article', to='cocoaApp.categorie_article')),
            ],
            options={
                'verbose_name': 'Arcticle',
                'verbose_name_plural': 'Arcticles',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('montant_total', models.FloatField()),
                ('etat_commande', models.CharField(max_length=200)),
                ('address_livraison', models.CharField(max_length=200)),
                ('address_facturation', models.CharField(max_length=200)),
                ('remise', models.FloatField()),
                ('etat_livraison', models.CharField()),
                ('date_livraison', models.DateField()),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrateur', to='cocoaApp.administrateur')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='cocoaApp.client')),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_paiement', to='cocoaApp.mode_paiement')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-etat_commande'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('note', models.IntegerField()),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaire_admin', to='cocoaApp.administrateur')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaire_article', to='cocoaApp.article')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaire_client', to='cocoaApp.client')),
                ('couturier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaire_couturier', to='cocoaApp.couturier')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('description', models.TextField()),
                ('etat_devis', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrateur_devis', to='cocoaApp.administrateur')),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_commande', to='cocoaApp.commande')),
                ('couturier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_couturier', to='cocoaApp.couturier')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(max_length=200)),
                ('montant', models.FloatField()),
                ('duree', models.IntegerField()),
                ('frequence_paiement', models.IntegerField()),
                ('data_paiement', models.DateField()),
                ('etat', models.CharField()),
                ('remise', models.FloatField()),
                ('nbre_renouvellement', models.IntegerField()),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyen_paiement', to='cocoaApp.mode_paiement')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-type_abonnement'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('abonnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='abonnement', to='cocoaApp.abonnement')),
                ('couturier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='couturier_souscription', to='cocoaApp.couturier')),
            ],
            options={
                'verbose_name': 'Souscription',
                'verbose_name_plural': 'Souscriptions',
                'ordering': ['-abonnement'],
            },
        ),
        migrations.CreateModel(
            name='Article_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='cocoaApp.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='cocoaApp.tag')),
            ],
            options={
                'verbose_name': 'Article_tag',
                'verbose_name_plural': 'Article_tags',
            },
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_vetement', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('disponibilite', models.CharField(max_length=200)),
                ('couturier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couturier', to='cocoaApp.couturier')),
            ],
            options={
                'verbose_name': 'Vetement',
                'verbose_name_plural': 'Vetements',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Vetement_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('couleur', models.CharField(max_length=200)),
                ('matiere', models.CharField(max_length=200)),
                ('taille', models.CharField(max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='cocoaApp.commande')),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetement', to='cocoaApp.vetement')),
            ],
            options={
                'verbose_name': 'Vetement_commande',
                'verbose_name_plural': 'Vetement_commandes',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='cocoaApp.pays')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='couturier',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_list', to='cocoaApp.ville'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_list', to='cocoaApp.ville'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_list', to='cocoaApp.ville'),
        ),
    ]
